import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Find Images',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={'max-w-6xl mx-auto'}>{children}</body>
    </html>
  );
}
