import Navbar from '@/components/Navbar';
import './globals.css';
import type { Metadata } from 'next';

export const revalidate = 3600; // 1 hour

export const metadata: Metadata = {
  title: 'Find Images',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <Navbar />
        <main className={'max-w-6xl mx-auto'}>{children}</main>
      </body>
    </html>
  );
}
